# Generated by Django 5.1.4 on 2024-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
